# Generated by Django 3.1.5 on 2021-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeurl',
            old_name='Url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='youtubeurl',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
